### ISSUE TITLE
Shadowed .foregroundColor

### ISSUE THREAD

**Issue by pawello2222** [zmian/xcore#90]
Hi @zmian 

I've noticed that `foregroundColor` shadows the native modifier:

- Xcore [foregroundColor](https://github.com/zmian/xcore/blob/86ef52c75c8b21d153d961d78a01913d03854673/Sources/SwiftUI/Extensions/View%2BExtensions.swift#L96):
```
func foregroundColor(_ color: UIColor) -> some View
```
- SwiftUI [foregroundColor](https://developer.apple.com/documentation/swiftui/view/foregroundcolor(_:)):
```
func foregroundColor(_ color: Color?) -> some View
```

Now, when we have Xcore imported, the following uses the UIColor which IMHO is not desired:
```
Text("Text")
    .foregroundColor(.red)
```

Is it possible to remove the shadowing? 

E.g. rename the modifier like in [here](https://github.com/pawello2222/xcore/commit/4080f7872036e2624a9a7d8aa47cd19e4cdad890):
```
public func foregroundUIColor(_ uiColor: UIColor) -> some View
```

If that's not something you'd like to change feel free to close this 😉

**Comment by zmian** [comment]
Hi @pawello2222,

The shadowing is needed for `UIColor`s that are not available in `SwiftUI.Color` struct. For example, all of the semantic colors (e.g., `UIColor.separator`) and theme colors. If I update theme to take `Color` it makes them incompatible with UIColors. 

I can rename the modifier as per your suggestion. As I believe this inconvenience is just temporary. Need SwiftUI to provide UIColor initializer that takes Color.

**Comment by zmian** [comment]
@pawello2222 I was able to add `@_disfavoredOverload` which always prefers `SwiftUI.Color` variant when present and only use the `UIKit.UIColor` when SwiftUI counter part doesn't exists. This addresses the original problem you had mentioned in much more streamlined way. As Apple starts to add more and more SwiftUI support the disfavored functions starts to gets used a lot less. This mean I can eventually deprecate UIColor version.


## Without `@_disfavoredOverload`
<img width="300" src="https://user-images.githubusercontent.com/621693/124528011-27c61e80-ddd5-11eb-8558-ac2e4ba3feb7.png">

## With `@_disfavoredOverload`
<img width="300"  src="https://user-images.githubusercontent.com/621693/124528050-3c0a1b80-ddd5-11eb-9d0c-e1cbe65fc78b.png">


The `UIColor` version is used correctly as `theme.textColor` is of type `UIColor`†
<img width="300" src="https://user-images.githubusercontent.com/621693/124528077-4a583780-ddd5-11eb-8fb9-28040adce05c.png">

**Comment by pawello2222** [comment]
@zmian This is exactly what I needed here. This definitely solves my problem 🎉 Thanks a lot 🙂
