### ISSUE TITLE
Ambiguity of `scaledEffect` in SwiftUI

### ISSUE THREAD

**Issue by pawello2222** [zmian/xcore#94]
Hi @zmian 

I've noticed an ambiguity when using SwiftUI `scaledEffect` with Xcore.

Because of CGSize conformance to `ExpressibleByIntegerLiteral` and `ExpressibleByFloatLiteral` as in [here](https://github.com/zmian/xcore/blob/3c1ef07d1db8b2118f1a548fd03edd690e83496a/Sources/Xcore/Swift/Extensions/Geometry%2BExtensions.swift#L193):
```
// MARK: - CGSize - ExpressibleByFloatLiteral
extension CGSize: ExpressibleByFloatLiteral {
    public init(floatLiteral value: FloatLiteralType) {
        let value = CGFloat(value)
        self = CGSize(width: value, height: value)
    }
}

// MARK: - CGSize - ExpressibleByIntegerLiteral
extension CGSize: ExpressibleByIntegerLiteral {
    public init(integerLiteral value: IntegerLiteralType) {
        let value = CGFloat(value)
        self = CGSize(width: value, height: value)
    }
}
```
there's an ambiguity between these SwiftUI modifiers:
```
@inlinable public func scaleEffect(_ s: CGFloat, anchor: UnitPoint = .center) -> some View
```
```
@inlinable public func scaleEffect(_ scale: CGSize, anchor: UnitPoint = .center) -> some View
```

Particularly when we try to apply `scaledEffect` to a SwiftUI View:
```
Text("Xcore")
    .scaleEffect(1.5)    // Ambiguous use of 'scaleEffect(_:anchor:)'
```

Do you think you can solve this issue? My current [solution](https://github.com/pawello2222/xcore/commit/34692564d09b10955ab91d5a536bd285c1fdf6af#diff-4153e0ac0e01291a4a980b7ec83f9eac775fe610740e9daf34e77976d7689d69) simply removes both conformances but I'm sure this can be solved in a better way. Please let me know what you think.

**Comment by zmian** [comment]
@pawello2222 I've noticed this as well. Let me spend sometime to think about this.

**Comment by zmian** [comment]
@pawello2222 there are 2 ways to solve this:

1. Remove the conformance - like you mentioned
2. Or, be explicit for the API usage: `.scaleEffect(CGFloat(1.5))`

It seems Apple's approach is to overload these api with CGFloat and CGSize, I think it's better to remove the conformances all together. I've put up a patch to fix this here: https://github.com/zmian/xcore/commit/506e1188745131b59efe5b71e657e08c68bbf3e1

**Comment by pawello2222** [comment]
Thank you @zmian for a quick fix. This solves all issues 🎉
